import { AbpHttpInterceptor } from '@abp/abpHttpInterceptor';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';

@NgModule({
    providers: [
        ApiServiceProxies.ConfigEmailsServiceProxy,        
        ApiServiceProxies.TemplatesServiceProxy,        
        ApiServiceProxies.SYS_PREFIXsServiceProxy,        
        ApiServiceProxies.SYS_CODEMASTERSsServiceProxy,        
        ApiServiceProxies.HoSosServiceProxy,        
        ApiServiceProxies.HopDongsServiceProxy,        
        ApiServiceProxies.UngViensServiceProxy,        
        ApiServiceProxies.DangKyKCBsServiceProxy,        
        ApiServiceProxies.LichSuLamViecsServiceProxy,        
        ApiServiceProxies.TinhThanhsServiceProxy,        
        ApiServiceProxies.TruongGiaoDichsServiceProxy,        
        ApiServiceProxies.NoiDaoTaosServiceProxy,   
        
        ApiServiceProxies.DynamicActionsServiceProxy,      
        ApiServiceProxies.DynamicFieldsServiceProxy,        
        ApiServiceProxies.RoleMappersServiceProxy,        
        ApiServiceProxies.KeywordDetailsServiceProxy,
        ApiServiceProxies.DocumentStatusesServiceProxy,
        ApiServiceProxies.Memorize_KeywordsesServiceProxy,

        ApiServiceProxies.TextBooksServiceProxy,
        ApiServiceProxies.PrioritiesServiceProxy,
        ApiServiceProxies.StoreDatasourcesServiceProxy,
        ApiServiceProxies.HardDatasourcesServiceProxy,
        ApiServiceProxies.CommandDatasourcesServiceProxy,

        ApiServiceProxies.DynamicDatasourceServiceProxy,
        ApiServiceProxies.LabelsServiceProxy,
        ApiServiceProxies.DynamicValuesServiceProxy,
        ApiServiceProxies.DynamicFieldsServiceProxy,
        ApiServiceProxies.SqlStoreParamsServiceProxy,
        ApiServiceProxies.SqlConfigDetailsServiceProxy,
        ApiServiceProxies.SqlConfigsServiceProxy,
        ApiServiceProxies.HistoryUploadsServiceProxy,
        ApiServiceProxies.SettingConfigsServiceProxy,
        ApiServiceProxies.DocumentHandlingsServiceProxy,
        ApiServiceProxies.VanbansServiceProxy,
        ApiServiceProxies.SchedulesServiceProxy,
        ApiServiceProxies.PromulgatedsServiceProxy,
        ApiServiceProxies.ReceiveUnitsServiceProxy,
        ApiServiceProxies.TypeHandesServiceProxy,
        ApiServiceProxies.DocumentHandlingDetailsServiceProxy,
        ApiServiceProxies.MemorizeKeywordsServiceProxy,
        ApiServiceProxies.DocumentDetailsServiceProxy,
        ApiServiceProxies.WorkDetailsServiceProxy,
        ApiServiceProxies.WordProcessingsServiceProxy,
        ApiServiceProxies.WorkAssignsServiceProxy,
        ApiServiceProxies.DocumentTypesServiceProxy,
        ApiServiceProxies.DocumentServiceProxy,
        ApiServiceProxies.MenusServiceProxy,

        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
